# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/My Drive/Classes/Fall 2023/FPGA Design/EEL5722-Projects/Lab 4  Display PS 2 Keyboard Input on a VGA Monitor/Lab4-Vivado/Lab4-Vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Classes/Fall 2023/FPGA Design/EEL5722-Projects/Lab 4  Display PS 2 Keyboard Input on a VGA Monitor/Lab4-Vivado/Lab4-Vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/My Drive/Classes/Fall 2023/FPGA Design/EEL5722-Projects/Lab 4  Display PS 2 Keyboard Input on a VGA Monitor/Lab4-Vivado/Lab4-Vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Classes/Fall 2023/FPGA Design/EEL5722-Projects/Lab 4  Display PS 2 Keyboard Input on a VGA Monitor/Lab4-Vivado/Lab4-Vivado.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
