# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/My Drive/Classes/Fall 2023/FPGA Design/EEL5722-Projects/Lab 5  Display an Image on a VGA Monitor/lab5_constraints.xdc

# IP: ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
